# -*- coding: utf-8 -*-
"""InferenceOnMNISTFashion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12Cjkg-MB3xgQvPPX-l-dgPq2yah2Hh7T
"""

import joblib
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import time
from tensorflow import keras
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from google.colab import files

print("Libraries imported successfully!")

model_filename = '/content/drive/MyDrive/ML project course/MNIST-FASHION/final_best_model.joblib'
scaler_filename = '/content/drive/MyDrive/ML project course/MNIST-FASHION/final_best_scaler.joblib'

print(f"Loading model from {model_filename}...")
model = joblib.load(model_filename)

print(f"Loading scaler from {scaler_filename}...")
scaler = joblib.load(scaler_filename)

print("\n--- Assets Loaded ---")
print("Model:")
print(model)
print("\nScaler:")
print(scaler)

class_names = ['T-shirt/top', 'Trouser', 'Pullover', 'Dress', 'Coat',
               'Sandal', 'Shirt', 'Sneaker', 'Bag', 'Ankle boot']

print("Loading fresh Fashion-MNIST test data...")
(_, _), (X_test_raw, y_test) = keras.datasets.fashion_mnist.load_data()

print(f"Raw test data shape: {X_test_raw.shape}")
print(f"Test labels shape: {y_test.shape}")

print("1. Flattening images...")
X_test_flat = X_test_raw.reshape(X_test_raw.shape[0], -1).astype('float32')
print(f"   Flattened data shape: {X_test_flat.shape}")

print("2. Applying pre-fitted StandardScaler...")
X_test_processed = scaler.transform(X_test_flat)
print(f"   Processed data shape: {X_test_processed.shape}")
print(f"   Processed data mean (approx): {X_test_processed.mean():.4f}")
print(f"   Processed data std (approx): {X_test_processed.std():.4f}")

print("\nData is ready for inference.")

N_SAMPLES_TO_TEST = 10

class_names = ['T-shirt/top', 'Trouser', 'Pullover', 'Dress', 'Coat',
               'Sandal', 'Shirt', 'Sneaker', 'Bag', 'Ankle boot']

print("Loading fresh Fashion-MNIST test data...")
(_, _), (X_test_raw, y_test) = keras.datasets.fashion_mnist.load_data()
print(f"Full test set loaded: {X_test_raw.shape[0]} images.")

my_samples_raw = X_test_raw[:N_SAMPLES_TO_TEST]
my_labels_true = y_test[:N_SAMPLES_TO_TEST]

print(f"\nSelected {N_SAMPLES_TO_TEST} samples for inference.")

print("Starting inference pipeline...")

my_samples_flat = my_samples_raw.reshape(N_SAMPLES_TO_TEST, -1).astype('float32')
print(f"1. Samples flattened to shape: {my_samples_flat.shape}")

my_samples_processed = scaler.transform(my_samples_flat)
print(f"2. Scaler applied. Processed shape: {my_samples_processed.shape}")

print("3. Running model.predict()...")
start_time = time.time()
my_predictions = model.predict(my_samples_processed)
end_time = time.time()

print(f"\n--- Inference Complete ---")
print(f"Time taken: {end_time - start_time:.4f} seconds.")
print(f"Predictions array: {my_predictions}")
print(f"True labels array: {my_labels_true}")

print("Visualizing predictions...")

ncols = 5
nrows = int(np.ceil(N_SAMPLES_TO_TEST / ncols))

fig, axes = plt.subplots(nrows, ncols, figsize=(ncols * 3.5, nrows * 4))
if nrows == 1:
    axes = np.array([axes])

for i, ax in enumerate(axes.flat):
    if i < N_SAMPLES_TO_TEST:
        img = my_samples_raw[i]
        true_label = class_names[my_labels_true[i]]
        pred_label = class_names[my_predictions[i]]

        color = 'green' if true_label == pred_label else 'red'

        ax.imshow(img, cmap='gray')
        ax.set_title(f'True: {true_label}\nPred: {pred_label}', fontsize=12, color=color, fontweight='bold')
        ax.axis('off')
    else:
        ax.axis('off')

plt.suptitle(f'Inference Results (Green=Correct, Red=Incorrect)', fontsize=16, y=1.02)
plt.tight_layout()
plt.show()

