# -*- coding: utf-8 -*-
"""InferenceOnCIFAR10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13Yx9_DhzVvYsuYnzRs_2WKDjCwiiCCKs
"""

import joblib
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras
import warnings

warnings.filterwarnings('ignore')

print("Libraries imported.")

model_filename = '/content/drive/MyDrive/ML project course/CIFAR-10/best_svm_model.joblib'
scaler_filename = '/content/drive/MyDrive/ML project course/CIFAR-10/best_scaler.joblib'

try:
    model = joblib.load(model_filename)
    print(f" Model '{model_filename}' loaded successfully!")
    print(f"   Model details: {model}")

    scaler = None
    try:
        scaler = joblib.load(scaler_filename)
        print(f" Scaler '{scaler_filename}' loaded successfully!")
        print(f"   Scaler details: {scaler}")
    except FileNotFoundError:
        print(f" Note: Scaler file '{scaler_filename}' not found.")
        print("   This is expected if your best normalization was 'none' or 'l2'.")

except FileNotFoundError:
    print(f"❌ ERROR: Model file '{model_filename}' not found.")
    print("   Please make sure you have uploaded the file to this Colab session.")

(_, _), (X_test, y_test) = keras.datasets.cifar10.load_data()

y_test = y_test.flatten()

class_names = ['airplane', 'automobile', 'bird', 'cat', 'deer',
               'dog', 'frog', 'horse', 'ship', 'truck']

print(f"Test data loaded. Image shape: {X_test.shape}, Label shape: {y_test.shape}")

def predict_sample(image_index, model, scaler, X_test, y_test, class_names):
    """
    Preprocesses, predicts, and displays a single sample from the test set.
    """
    original_image = X_test[image_index]
    true_label_index = y_test[image_index]
    true_label_name = class_names[true_label_index]
    image_flat = original_image.reshape(1, -1).astype('float32')

    if scaler is not None:
        image_processed = scaler.transform(image_flat)
    else:
        print("-> No scaler used (assuming 'none' normalization).")
        image_processed = image_flat

    prediction = model.predict(image_processed)
    predicted_label_index = prediction[0]
    predicted_label_name = class_names[predicted_label_index]

    is_correct = (true_label_name == predicted_label_name)
    title_color = 'green' if is_correct else 'red'

    plt.figure(figsize=(4, 4))
    plt.imshow(original_image)
    plt.title(f"True: {true_label_name}\nPredicted: {predicted_label_name}",
              color=title_color, fontweight='bold')
    plt.axis('off')
    plt.show()

    print("-" * 30)
    print(f"Sample Index: {image_index}")
    print(f"True Label:     {true_label_name} ({true_label_index})")
    print(f"Predicted Label: {predicted_label_name} ({predicted_label_index})")
    print(f"Result: {'CORRECT' if is_correct else 'INCORRECT'}")
    print("=" * 30 + "\n")

if 'model' in locals():
    print("Running inference on 5 random samples from the test set...")

    random_indices = np.random.choice(len(X_test), 5, replace=False)

    for idx in random_indices:
        predict_sample(idx, model, scaler, X_test, y_test, class_names)
else:
    print("Model not loaded. Please run Cell 1 successfully first.")

